# Generated by Django 5.0.1 on 2024-02-07 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_app', '0009_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 1, 18, 27, 598809, tzinfo=datetime.timezone.utc)),
        ),
    ]
