# Generated by Django 5.0.1 on 2024-02-07 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_app', '0010_task_is_completed_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 21, 50, 30, 660042, tzinfo=datetime.timezone.utc)),
        ),
    ]
