# Generated by Django 5.0.1 on 2024-02-08 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_app', '0013_alter_task_due_date_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 1, 35, 58, 301519, tzinfo=datetime.timezone.utc)),
        ),
    ]
